package com.scorpmod;

import java.util.Arrays;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.item.ItemStack;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;

import com.scorpmod.blocks.BlockHandScanner;
import com.scorpmod.blocks.BlockScorp;
import com.scorpmod.libs.Reference;
import com.scorpmod.tileentity.HandScannerTile;

@Mod(modid = Reference.MOD_ID, name = Reference.MOD_NAME, version = Reference.MOD_VERSION)
public class ScorpMod
{
	public static Block scorpBlock;
	public static Block blockcommanderAdz;
	public static Block blockhandScanner;
	public static Block blockliquidMixer;
	public static Block blockliquidWasher;
	public static Block blockliquidBottler;
	
	public static Block blockwhiteFluid;
	public static Block blockgreenFluid;
	public static Block blockpurpleFluid;
	public static Block blockredFluid;
	public static Block blockturquoiseFluid;
	public static Block blockyellowFluid;
	
	
    @EventHandler
    public void preinit(FMLPreInitializationEvent event)
    {
    	ModMetadata data = event.getModMetadata();
        data.name = Reference.MOD_NAME;
        data.version = Reference.MOD_VERSION;
        data.authorList = Arrays.asList(new String[] {"Scorp"});
        data.description = Reference.MOD_DESCRIPTION;
        data.autogenerated = false;
        
        
		scorpBlock = new BlockScorp();
		registerBlock(scorpBlock, "Scorp Block");
		
		blockhandScanner = new BlockHandScanner();
		registerBlock(blockhandScanner, "Hand Scanner");
		
		GameRegistry.registerTileEntity(HandScannerTile.class, "HandScannerTile");
    }
    
    @EventHandler
    public void init(FMLInitializationEvent event)
    {
    }
    
    public static void registerBlock(Block block, String name){
    	GameRegistry.registerBlock(block, name);
    }
}
