package com.scorpmod;

import java.util.Arrays;

import net.minecraft.block.Block;

import com.scorpmod.blocks.ModBlocks;
import com.scorpmod.libs.Reference;
import com.scorpmod.proxy.CommonProxy;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;

@Mod(modid = Reference.MOD_ID, name = Reference.MOD_NAME, version = Reference.MOD_VERSION)
public class ScorpMod
{
	@SidedProxy(clientSide = "com.scorpmod.proxy.CommonProxy", serverSide = "com.scorpmod.proxy.ClientProxy")
	public static CommonProxy	proxy;
	@Instance(Reference.MOD_ID)
    public static ScorpMod instance;
    
	
	
	
    @EventHandler
    public void preinit(FMLPreInitializationEvent event)
    {
    	ModMetadata data = event.getModMetadata();
        data.name = Reference.MOD_NAME;
        data.version = Reference.MOD_VERSION;
        data.authorList = Arrays.asList(new String[] {"Scorp"});
        data.description = Reference.MOD_DESCRIPTION;
        data.autogenerated = false;
        
        ModBlocks.init();
		
    }
    
    @EventHandler
    public void init(FMLInitializationEvent event)
    {
    }
    
    public static void registerBlock(Block block, String name){
    	GameRegistry.registerBlock(block, name);
    }
}
